add issues templates
GDGAlgiers/.github pull request #2
Opened 2022-09-25 14:31 UTC by CerineBnsd

# Summary
This PR adds different issue templates. Templates help organizing the issues in categories, and help making sure that all the needed details are provided. (See an [example of issue template chooser](https://github.com/RITlug/teleirc/issues/new/choose)) 

# Description
The following templates are added:
- **New feature:** Suggest a new idea for the project.
- **Improvement:** Suggest an improvement to an existing functionality.
- **Refactor:** Refactor the codebase, or a part of it.
- **Bug Report:** Report a bug in the project.
- **Testing:** Add, improve or edit tests in the codebase.

The `config.yml` file is used to customize the templates chooser. (see: [Configuring the template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser))

# Further work
Once the custom labels are configured for the organization, we can add labels (metadata) in the templates. This will automatically tag the created issue with the specified labels.

2022-09-25 20:05 UTC, youben11 requested changes

2022-09-25 20:05 UTC, youben11 commented on README.md
> +# GDG Algiers contributing guidelines
Shouldn't it include something like "default community health files"?

2022-09-25 20:05 UTC, youben11 commented on .github/ISSUE_TEMPLATE/new-feature.md
> +State the different existing features that will be broken/affected by this new feature.
what about "borken/affected (if any)"?

2022-09-25 20:05 UTC, youben11 commented on .github/ISSUE_TEMPLATE/improvement.md
> +Describe briefly what the end results will be, once this issue is solved.
typo: "end result"

2022-09-25 20:05 UTC, youben11 commented on .github/ISSUE_TEMPLATE/bug-report.md
> +Past logs here between the quotes
I think they are called "backticks". But we can just keep the "Past logs here"

2022-09-25 20:59 UTC, CerineBnsd commented on README.md
> +# GDG Algiers contributing guidelines
Exactly, I wanted to discuss this, and yes, this is more expressive.

2022-10-02 08:30 UTC, youben11 approved these changes

2022-10-05 16:29 UTC, merged